spring:
  datasource:
    url: jdbc:h2:mem:SSN
    driver-class-name: org.h2.Driver
    username: user
  jpa:
    properties:      hibernate:
        show_sql: true
        format_sql: true    database-platform: org.hibernate.dialect.H2Dialect
    
server:  port: 9935    
    